# Primeros pasos

In [ ]:
2*3

6

In [ ]:
2**3

8

In [ ]:
x = 12
x

12

In [ ]:
y = 15

In [ ]:
x + y

27

In [ ]:
x = 'Hola'
y = 'Mundo'
x + y

'HolaMundo'

In [ ]:
x +  ' ' +  y

'Hola Mundo'

In [ ]:
[1,2,3,4] + [2,3,4]

[1, 2, 3, 4, 2, 3, 4]

In [ ]:
lista = [1,2,3,4,5]

In [ ]:
lista[0]

1

In [ ]:
lista[2]

3

In [ ]:
lista[-1]

5

In [ ]:
[1,2,3,4,5] + [10]

[1, 2, 3, 4, 5, 10]

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.array([1,2,3,4,5]) + 10

array([11, 12, 13, 14, 15])

In [ ]:
np.array([1,2,3,4,5]).shape

(5,)

In [ ]:
np.array([[1,2,3,4],[6,7,8,9]])

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [ ]:
np.array([[1,2,3,4],[6,7,8,9]]).shape

(2, 4)

In [ ]:
np.array([[1,2,3,4],[6,7,8,9]])[0]

array([1, 2, 3, 4])