In [ ]:
2*3

6

In [ ]:
2**3

8

In [ ]:
x = 12
x

12

In [ ]:
y = 15

In [ ]:
x + y

27

In [ ]:
x = 'Hola'
y = 'Mundo'
x + y

'HolaMundo'

In [ ]:
x +  ' ' +  y

'Hola Mundo'

In [ ]:
[1,2,3,4] + [2,3,4]

[1, 2, 3, 4, 2, 3, 4]

In [ ]:
lista = [1,2,3,4,5]

In [ ]:
lista[0]

1

In [ ]:
lista[2]

3

In [ ]:
lista[-1]

5

In [ ]:
[1,2,3,4,5] + [10]

[1, 2, 3, 4, 5, 10]

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.array([1,2,3,4,5]) + 10

array([11, 12, 13, 14, 15])

In [ ]:
np.array([1,2,3,4,5]).shape

(5,)

In [ ]:
np.array([[1,2,3,4],[6,7,8,9]])

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [ ]:
np.array([[1,2,3,4],[6,7,8,9]]).shape

(2, 4)

In [ ]:
np.array([[1,2,3,4],[6,7,8,9]])[0]

array([1, 2, 3, 4])

In [ ]:
np.array([[1,2,3,4],[6,7,8,9]])[0][2]

3

# Series

In [ ]:
import pandas as pd

In [ ]:
pd.Series([10,9,8,7,6])

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [ ]:
sr = pd.Series([10,9,8,7,6])
sr

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [ ]:
sr.values

array([10,  9,  8,  7,  6])

In [ ]:
sr.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
sr.shape

(5,)

In [ ]:
sr[3]

7

In [ ]:
sr[[0,4,2]]

0    10
4     6
2     8
dtype: int64

In [ ]:
sr = pd.Series([10,9,8,7,6], index = ['a','b','c','d','e'])
sr

a    10
b     9
c     8
d     7
e     6
dtype: int64

In [ ]:
sr['c']

8

In [ ]:
sr[['c','d','e']]

c    8
d    7
e    6
dtype: int64

In [ ]:
sr['b':'e']

b    9
c    8
d    7
e    6
dtype: int64

In [ ]:
dict_data = {'CO':100,'MX':200,'AR':300}
dict_data

{'AR': 300, 'CO': 100, 'MX': 200}

In [ ]:
dict_data.keys()

dict_keys(['CO', 'MX', 'AR'])

In [ ]:
dict_data['MX']

200

In [ ]:
pd.Series(dict_data)

CO    100
MX    200
AR    300
dtype: int64

In [ ]:
pd.Series(dict_data, index=['CO','MX','PE'])

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [ ]:
import numpy as np

In [ ]:
np.nan

nan

In [ ]:
np.nan + 10

nan

In [ ]:
np.nan * 10

nan

In [ ]:
sr = pd.Series(dict_data, index=['CO','MX','PE'])
sr

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [ ]:
sr.isnull()

CO    False
MX    False
PE     True
dtype: bool

In [ ]:
sr.notnull()

CO     True
MX     True
PE    False
dtype: bool